export const ADD_ITEM_TO_SHOPPING_LIST = "ADD_ITEM_TO_SHOPPING_LIST"
export const REMOVE_ITEM_FROM_SHOPPING_LIST = "REMOVE_ITEM_FROM_SHOPPING_LIST"
export const TOGGLE_ITEM_IN_CART = "TOGGLE_ITEM_IN_CART"
